### ISSUE TITLE
nodebb crash, not sure how it's happening

### ISSUE THREAD

**Issue by nickjanssen** [julianlam/nodebb-plugin-markdown#39]
One particular post on our forum somehow crashes everything:
nodebb sha b917235

```
##**Join the Guardians of the Peaks!**
####***Righteousness. Courage. Benevolence. Respect. Sincerity. Honor. Loyalty. Self-Control.***
---
[Link to Guild Registration](http://goo.gl/forms/pKvtcErOLB)
![]()
![]()

###**Current members:**
Thaiberius - Diplomat; Owner

DomTheDoom - Fighter; Officer

ironman123 - Fighter; Officer

yoshifan509 - Healer; Officer

---
###**Roles**
**Officer:** Officers recruits members and have direct control over anybody of lower status. If a member feels they are being treated unfair, they can contact another officer or Thaiberius.

**Fighter:** Fighters play a large role in the guild. They (obviously) fight monsters and bosses and participate in guild wars. The fighters also play the role of collecting loot for the rest of the guild. A fighter can be promoted to Champion if they can defeat the rest of the guild fighters or have the highest Arena Rank of all the fighters.

**Healer:** Healers are the fighters' best friends. When in battle, a healer will make sure nobody falls and, if one does, will gather their loot and place it in their guild inventory. Healers, being the least wanted of all the roles, will receive extra guild loot.

**Diplomat:** Diplomats have the same "social status" as the owner. Diplomats are direct speakers for the guild and arrange all the events for the guild.

---
####**Other Roles [Specified in "Other"]**
**Scouts:** Scouts have the role of exploring and adventuring Ironbane.

**Military Advisers:** A military adviser plays the role of assigning fighters and healers to look for loot in certain areas of the map. These areas can be specified by scouts.

**Treasurer:** Treasurers divide up the loot for the whole guild. Only good friends of mine (people I trust) can become a treasurer. A treasurer who has "messed up" more than twice will be forever banned from the guild, unless voted back by 67% of the guild (like passing a bill. Otherwise, I can veto it).

**Welcomers:** Assigned to the friendliest officers. The welcomers (obviously) welcome new guild members and are required to help them out until they say they can be on their own. The welcomers will declare the guild rules as soon as they are enlisted. Guild rules will be added after a fair amount of members join.

---
```

Server log:
```
29/4 04:42 [1] - error: TypeError: Cannot read property 'toString' of null
    at Object.Markdown.isUrlValid (/opt/nodebb/node_modules/nodebb-plugin-markdown/index.js:168:49)
    at Object.parser.renderer.rules.image (/opt/nodebb/node_modules/nodebb-plugin-markdown/index.js:152:20)
    at Renderer.renderInline (/opt/nodebb/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/renderer.js:235:28)
    at Renderer.render (/opt/nodebb/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/renderer.js:289:22)
    at MarkdownIt.render (/opt/nodebb/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/index.js:510:24)
    at Object.Markdown.parsePost [as method] (/opt/nodebb/node_modules/nodebb-plugin-markdown/index.js:92:37)
    at /opt/nodebb/src/plugins/hooks.js:89:12
    at /opt/nodebb/node_modules/async/lib/async.js:272:13
    at iterate (/opt/nodebb/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/opt/nodebb/node_modules/async/lib/async.js:165:9)
TypeError: Cannot read property 'toString' of null
    at Object.Markdown.isUrlValid (/opt/nodebb/node_modules/nodebb-plugin-markdown/index.js:168:49)
    at Object.parser.renderer.rules.image (/opt/nodebb/node_modules/nodebb-plugin-markdown/index.js:152:20)
    at Renderer.renderInline (/opt/nodebb/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/renderer.js:235:28)
    at Renderer.render (/opt/nodebb/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/renderer.js:289:22)
    at MarkdownIt.render (/opt/nodebb/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/index.js:510:24)
    at Object.Markdown.parsePost [as method] (/opt/nodebb/node_modules/nodebb-plugin-markdown/index.js:92:37)
    at /opt/nodebb/src/plugins/hooks.js:89:12
    at /opt/nodebb/node_modules/async/lib/async.js:272:13
    at iterate (/opt/nodebb/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/opt/nodebb/node_modules/async/lib/async.js:165:9)
```

Any ideas?

**Comment by nickjanssen** [comment]
Apparently the
```
![]()
![]()
```
causes it. But the official nodebb forum seems to be immune. I wonder why...

**Comment by Thaiberius** [comment]
Also leaves 502 error.

**Comment by julianlam** [comment]
#36 may have resolved this. Please install v2.1.7 of the markdown plugin and give it a go :smile:

**Comment by julianlam** [comment]
As for why the official forum is immune, most likely we have not updated to the version of the markdown plugin that contains this bug :laughing: 

Let me know if it is resolved with latest published version, and we can close this.

**Comment by rbeer** [comment]
LGTM @ 3.0.4

**Comment by julianlam** [comment]
Cheers
