### ISSUE TITLE
Unable to parse library

### ISSUE THREAD

**Issue by youhosi** [julianlam/nodebb-plugin-markdown#97]
```
2018-11-18T13:34:01.334Z [15618] - error: Error: Cannot find module '../meta'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Object.<anonymous> (/var/www/forum/node_modules/nodebb-plugin-markdown/index.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.Plugins.requireLibrary (/var/www/forum/src/plugins.js:43:32)
    at registerHooks (/var/www/forum/src/plugins/load.js:183:13)
    at /var/www/forum/src/plugins/load.js:141:6
    at /var/www/forum/node_modules/async/dist/async.js:3880:24
    at eachOfArrayLike (/var/www/forum/node_modules/async/dist/async.js:1069:9)
2018-11-18T13:34:01.341Z [15620] - error: Error: Cannot find module '../meta'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Object.<anonymous> (/var/www/forum/node_modules/nodebb-plugin-markdown/index.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.Plugins.requireLibrary (/var/www/forum/src/plugins.js:43:32)
    at registerHooks (/var/www/forum/src/plugins/load.js:183:13)
    at /var/www/forum/src/plugins/load.js:141:6
    at /var/www/forum/node_modules/async/dist/async.js:3880:24
    at eachOfArrayLike (/var/www/forum/node_modules/async/dist/async.js:1069:9)
2018-11-18T13:34:01.343Z [15620] - warn: [plugins] Unable to parse library for: nodebb-plugin-markdown
2018-11-18T13:34:01.347Z [15618] - warn: [plugins] Unable to parse library for: nodebb-plugin-markdown
2018-11-18T13:34:01.373Z [15617] - error: Error: Cannot find module '../meta'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Object.<anonymous> (/var/www/forum/node_modules/nodebb-plugin-markdown/index.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.Plugins.requireLibrary (/var/www/forum/src/plugins.js:43:32)
    at registerHooks (/var/www/forum/src/plugins/load.js:183:13)
    at /var/www/forum/src/plugins/load.js:141:6
    at /var/www/forum/node_modules/async/dist/async.js:3880:24
    at eachOfArrayLike (/var/www/forum/node_modules/async/dist/async.js:1069:9)
2018-11-18T13:34:01.379Z [15617] - warn: [plugins] Unable to parse library for: nodebb-plugin-markdown
```

**Comment by julianlam** [comment]
Should already be fixed on latest, what version are you using?

**Comment by youhosi** [comment]
I used version 8.8.2.

**Comment by pitaj** [comment]
What node version?

**Comment by youhosi** [comment]
v10.13.0

**Comment by julianlam** [comment]
v8.8.3

**Comment by julianlam** [comment]
v8.8.4

**Comment by youhosi** [comment]
I have updated, reloaded resources, the error does not show, but the plugin does not work. There is also no tab to manage it.

![zrzut ekranu z 2018-11-19 18-39-20](https://user-images.githubusercontent.com/24297084/48724789-76294d80-ec2a-11e8-8c3d-8735028b3a93.png)

**Comment by pitaj** [comment]
Did you run rebuild and restart?

**Comment by youhosi** [comment]
yes

**Comment by youhosi** [comment]
```
oxide@:~/forum$ npm install nodebb-plugin-markdown@8.8.4
...
oxide@:~/forum$ ./nodebb build; ./nodebb start; ./nodebb log
...
started
2018-11-19T17:34:48.952Z [19197] - info: [build] Building in parallel mode
...
Starting NodeBB
...

2018-11-19T17:27:04.149Z [19102] - info: NodeBB Ready
2018-11-19T17:27:04.154Z [19105] - info: Routes added
2018-11-19T17:27:04.156Z [19103] - info: Enabling 'trust proxy'
2018-11-19T17:27:04.160Z [19102] - info: Enabling 'trust proxy'
2018-11-19T17:27:04.166Z [19102] - info: NodeBB is now listening on: 0.0.0.0:xxx
2018-11-19T17:27:04.167Z [19103] - info: NodeBB is now listening on: 0.0.0.0:xxx
2018-11-19T17:27:04.168Z [19105] - info: NodeBB Ready
2018-11-19T17:27:04.175Z [19105] - info: Enabling 'trust proxy'
2018-11-19T17:27:04.180Z [19105] - info: NodeBB is now listening on: 0.0.0.0:xxx
Missing key in translation token "text"
```

**Comment by julianlam** [comment]
You don't separate commands with `;`. That means they run in background and the next command is executed. Separate commands with `&&`

**Comment by youhosi** [comment]
thanks, works :)
